### ISSUE TITLE
org-node-insert-link doesn't use region

### ISSUE THREAD

**Issue by emacsomancer** [meedstrom/org-node#10]
Given the function definition, as far as I can tell, it seems that `org-node-insert-link` should (desirably) behave differently if there's an active region (like `org-roam-node-insert` does), but in practice it seems to ignore the region, at least as far as (pre-)searching the index for selected text/region.

**Comment by emacsomancer** [comment]
Yes, either a region that's a substring of a node I think I already have, or else one I want to create. (Sometimes I've typed out a bunch of things first, and am going back to add links/nodes.)

**Comment by meedstrom** [comment]
Alright, not sure I like it as a default, so I made an alternative command `org-node-insert-link*` :)

**Comment by meedstrom** [comment]
What's your `org-node-creation-fn`? I guess `org-node-new-by-roam-capture`?  Does it happen with all your capture templates or only some?

**Comment by emacsomancer** [comment]
Yes, I have `(setq org-node-creation-fn #'org-node-new-by-roam-capture)` in my config, as per the example.

I'm just trying calling `org-node-insert-link(*)` directly, and it happens with both.

The only thing I can think is that I use `vertico` and have `C-j` setup in order to force enter with a non-match via 

````
....
:bind (:map vertico-map
              ("C-j" . vertico-exit-input))
...
````

in my vertico setup.

**Comment by meedstrom** [comment]
Then if you turn off vertico-mode, it works?

**Comment by emacsomancer** [comment]
> Then if you turn off vertico-mode, it works?

No, same thing, even with vertico turned off.

Not sure where the arrayp check comes from.

**Comment by emacsomancer** [comment]
(It doesn't happen with `org-node-find`.)

**Comment by meedstrom** [comment]
That is when you use `org-node-find` to create a new node, it works?

Got anything in `'org-node-insert-link-hook`?

Also, got the newest version of this package? :)  What's your Emacs version, btw?

**Comment by emacsomancer** [comment]
Yes, I can create new nodes with `org-node-find`.

`org-node-insert-link-hook` is `nil`. 

I updated all packages this morning. 

I'm using Emacs 30.0.50, fairly close to master.
