### ISSUE TITLE
Circular-list problem with multiple keyword sets

### ISSUE THREAD

**Issue by claudiusmueller** [meedstrom/org-node#14]
I'm setting my orgmode keywords like this in the init file:

```
(setq org-todo-keywords
      '((sequence "TODO(t)" "|" "DONE(d)" "CANCELED(c)")
        (sequence "TASK(a)" "|" "FINISHED(f)" "DROPPED(r)")
        (sequence "IDEA(i)" "|" "SCRAPPED(x)")))
```

When I turn on org-node with:

```
  (use-package org-node
    :straight (org-node :type git :host github :repo "meedstrom/org-node")
    :hook (org-mode . org-node-cache-mode))
```

I get this error when saving an org file:

```
org-node-cache--collect*: List contains a loop: ("FINISHED(f)" "DROPPED(r)" "IDEA(i)" "|" "SCRAPPED(x)" "TASK(a)" "|" "FINISHED(f)" "DROPPED(r)" "IDEA(i)" ...)
```

and this when opening another org file:

```
File mode specification error: (circular-list (DROPPED(r) IDEA(i) | SCRAPPED(x) TASK(a) | FINISHED(f) DROPPED(r) IDEA(i) | SCRAPPED(x) TASK(a) | . #6))
```

If I limit my setup to a single keyword set like this:

```
(setq org-todo-keywords
      '((sequence "TODO(t)" "|" "DONE(d)" "CANCELED(c)")))
```

then I don't have this problem.

Somehow org-node seems to be incompatible with multiple keyword sets?

**Comment by meedstrom** [comment]
That’s a very interesting error. Circular list? Maybe something is going
wrong with how arguments are passed in `org-node-worker--make-todo-regexp`.

Thanks for reporting! I’ll be back from my trip on 27 May and I’ll try to
fix it then.

**Comment by claudiusmueller** [comment]
Thanks - appreciated!

**Comment by meedstrom** [comment]
Ah, I found the problem.  Turns out that `mapcan` mutates the input variable using `nconc`.  Guess the hint was in the function name ending in "n".  Changed it to the non-destructive `-mapcat` and we're good.
