### ISSUE TITLE
regret is broken

### ISSUE THREAD

**Issue by emacsomancer** [meedstrom/org-node#16]
`org-node-backlink-regret` doesn't work as an interactive command. (I did end up regretting backlinks, partially because (probably due to font-locking things I have in my Org? maybe?) any node with a significant number of backlinks end up causing Emacs to freeze for long periods of time when displaying the :BACKLINKS: property in the property block.)

The function is currently defined to have an argument, which it doesn't get when used interactively, and so it fails with an error. And the argument is actually unused in the function definition, so I think it probably should just be removed.

**Comment by meedstrom** [comment]
Oh, yea, I did remove that superfluous argument a few days ago :) Let me know if it works after update.
