### ISSUE TITLE
straight not loading latest master from github

### ISSUE THREAD

**Issue by iantor** [meedstrom/org-node#19]
I have the standard straight config:

(use-package org-node
  :straight (org-node :type git :host github :repo "meedstrom/org-node")
  :hook (org-mode . org-node-cache-mode))

the version code in org-node.el is still 1.0pre, whereas the code in current master is 0.3pre.
How can I have straight load the latest version?

**Comment by meedstrom** [comment]
I think this is a matter of ask Straight to upgrade all your packages.
(Since I use Doom Emacs, I tend to do it with `doom upgrade`.) Let me know
if that does not help.

**Comment by iantor** [comment]
Indeed, I was able to upgrade all the packages. Thanks.

**Comment by meedstrom** [comment]
Just bumped to 0.3 fwiw ;)
