### ISSUE TITLE
org-node-rename-file-by-title edge-cases

### ISSUE THREAD

**Issue by emacsomancer** [meedstrom/org-node#24]
`org-node-rename-file-by-title` perhaps still needs some tweaking. I've found it doesn't always do the expected thing (I may need to play with `org-node-slug-fn` a bit, admittedly). But one case that's an issue is for (at least how my Org Roam dailies are named) dailies, if they are named as `<YYYY-MM-DD>.org`.

**Comment by meedstrom** [comment]
Mine are also named that! (Without angle brackets, e.g. 2024-08-02.org, and they have a `#+title: 2024-08-02` inside).

Anyway, it shouldn't do anything to files in `org-roam-dailies-directory`. Maybe there's a mistake in the code? What behavior is unexpected?

**Comment by meedstrom** [comment]
Actually, if called interactively, it will follow the usual rules even in the dailies directory.  On a hook it won't do that.

**Comment by emacsomancer** [comment]
If it's called interactively on file in the org-roam-dailies directory that's named "2021-07-30.org", it renames it to "2021-2021_07_30.org", which seems undesirable.

**Comment by meedstrom** [comment]
Thanks, I guess you have experience with this kind of code from org-roam-daily-reflection? ;)

To restrict the scope of org-node, I am actually thinking of suggesting that people configure [org-journal](https://github.com/bastibe/org-journal) to do something equivalent to Roam's dailies (and show an example snippet), but I am not sure if it would be feature-complete. Need to trial it.

At the least, we do need to ship a specialized capture target.  I committed the experimental function `org-node--daily-capture-target` some time ago, but it's untested.

**Comment by emacsomancer** [comment]
Ah, well, I was thinking sort of the opposite direction (having an `org-node-dailies-directory` variable and improving functions around dailies, including making the find-next, find-prev functions smarter[0]). I can say that using the org-node dailies functions from this commit has made the Termux/Android experience much better.

But I've never tried org-journal before. And I think limiting package scope is a very good practice, so it seems worth exploring. (On the other hand, it feels like a lot can be done with 'dailies' that would largely take advantage of existing org-node things, without requiring major infrastructure.)

[0]: Like a hash table for dailies that could be searched, rather than the naive thing they're doing now, which is just cycling through every calendarically-possible date before/after the source/current node and seeing if org-node has an entry for it

**Comment by meedstrom** [comment]
Nice quote by Jamie Zawinski btw :)

Experimenting... it's, ah, doesn't really expect files with no headings at all so sometimes I get an error, but this config looks like a good start:

```elisp
(add-hook 'org-journal-after-header-create-hook #'org-node-nodeify-entry)
(setq org-journal-dir "/home/kept/roam/daily")
(setq org-journal-file-format "%F.org")
(setq org-journal-date-prefix "#+title: ")
(setq org-journal-date-format "%F")
(setq org-journal-time-prefix "")
(setq org-journal-time-format "")
```

(By default, org-journal creates a heading for the day and then a subheading for each time you invoke `org-journal-new-entry`)

**Comment by emacsomancer** [comment]
I haven't looked much into `org-journal` so far. Does `org-journal` have good built-in look-ups for (ts equivalent of) "dailies"? The advantage of trying to leverage existing `org-node` things is the fact that the look-ups themselves are all hash table things, and it's only the actual opening of files that touches the file-system itself. From what see for `org-journal`, looking quickly, is that its previous and next entry functions ultimately rely on `org-journal--list-files`, which looks at actual files, so in cases where it's the file system slowing things down, I wonder if this would also be slow (compared to doing look-ups in an internal hash table).

**Comment by meedstrom** [comment]
Hm. I don't know if you noticed, but `org-node-files` no longer memoizes its own result. Noticed any slowness creating new nodes on Termux?

But, I did that because after wrapping it in `(let ((file-name-handler-alist nil)))`, I figured it will feel fast enough on almost all devices.  Org-journal does not do that, so it'll be a bit slower. And if it re-runs that for every file you cycle through, cycling could suck.

**Comment by meedstrom** [comment]
Speaking of filesystem slowness, how fast is this on Termux? :)

: (progn (byte-compile #'org-node-files) (garbage-collect) (benchmark-run 100 (org-node-files)))

**Comment by emacsomancer** [comment]
I haven't specifically noticed slowness opening new nodes, but there is a large amount of general slowness, most noticeable to me when opening *existing* nodes.

Trying ` (progn (byte-compile #'org-node-files) (garbage-collect) (benchmark-run 100 (org-node-files)))` on Android and it's still running. I tried ` (progn (byte-compile #'org-node-files) (garbage-collect) (benchmark-run 1 (org-node-files)))` and that took over 19 seconds, so I predict about half an hour for the 100 run. 

So maybe for cases where there are large filesystem penalties for dealing with large numbers of files, memoising would be better?

**Comment by meedstrom** [comment]
Dang, that's fairly extreme... Interesting device!

**Comment by emacsomancer** [comment]
(This is on a Pixel 6 with just internal storage [Pixels don't have sdcard slots], so not something that's a particularly slow device - I think this is just a result of how Google does the 'mounting' of internal storage via some sort of FUSE method (I think it's `overlayfs` (since I think `sdcardfs` was retired), but I'm not entirely sure. 

Doing Org-Roam stuff is much worse on a tablet with the Org files on an actual sdcard.)

**Comment by emacsomancer** [comment]
> Speaking of filesystem slowness, how fast is this on Termux? :)
> 
> ```
>  (progn (byte-compile #'org-node-files) (garbage-collect) (benchmark-run 100 (org-node-files)))
> ```
> 
> My result (4.306949893 15 1.7982248850000015), i.e. 4.3 seconds, of which 1.7 seconds garbage collection. That means a single run takes 0.04s, which is totally ok.

Result: `(2288.3390021339997 116 34.445275407999986)`

**Comment by emacsomancer** [comment]
(This is on a Pixel 6 with just internal storage [Pixels don't have sdcard slots], so not something that's a particularly slow device - I think this is just a result of how Google does the 'mounting' of internal storage via some sort of FUSE method (I think it's `overlayfs` (since I think `sdcardfs` was retired), but I'm not entirely sure. 

Doing Org-Roam stuff is much worse on a tablet with the Org files on an actual sdcard.)

**Comment by meedstrom** [comment]
Do all your dailies have an ID?

I think this'll alleviate filesystem slowness. May ship it.

```elisp
(advice-add 'org-journal--list-files :override
            (defun org-node--list-journal-files ()
              "Faster than `org-journal--list-files'."
              (require 'org-journal)
              (cl-loop with re = (org-journal--dir-and-file-format->pattern)
                       for file in (org-node-list-files t)
                       when (and (string-match-p re file)
                                 (or org-journal-encrypt-journal
                                     (not (string-suffix-p "\\.gpg" file))))
                       collect file)))
```

**Comment by emacsomancer** [comment]
Yes, all my dailies have IDs.  

I'm trying this out.

I'm noticing that there are various things slowing down the `*org-roam*` buffer which might be switched off. I'm trying to measure things with the profiler. I'm half-wondering if an option just to dispense entirely with the font-locking might be a possible option for Android/Termux, just to eke out even a little more performance. I'll try to measure things over the next couple of days.

One issue I've run into is that some things mess up the construction of the buffers (a node changed its filename and org-node doesn't yet know about the name change; some sort of font-locking or other issue occurs) and these things mean that the buffer is never entirely constructed and so (I think; still testing things) it ends up being rebuilt (or attempted to be rebuilt) the next time that node's backlinks are open(ed).

**Comment by meedstrom** [comment]
New readme section may interest you https://github.com/meedstrom/org-node?tab=readme-ov-file#tip-on-very-slow-filesystems

> One issue I've run into is that some things mess up the construction of the buffers (a node changed its filename and org-node doesn't yet know about the name change; some sort of font-locking or other issue occurs) and these things mean that the buffer is never entirely constructed and so (I think; still testing things) it ends up being rebuilt (or attempted to be rebuilt) the next time that node's backlinks are open(ed).

Replying in #26.

**Comment by meedstrom** [comment]
> I'm half-wondering if an option just to dispense entirely with the font-locking might be a possible option for Android/Termux, just to eke out even a little more performance.

I have a giant file where I've found Org to be faster with these file-local settings, FWIW.

# -*- jit-lock-contextually: nil;  jit-lock-defer-time: 0; -*-
