### ISSUE TITLE
feature(?): caching contents of backlinks buffer

### ISSUE THREAD

**Issue by emacsomancer** [meedstrom/org-node#26]
I wonder if it would be possible to (optionally) cache the output of the backlinks buffer (`*org-roam*` buffer).

Nodes with lots of backlinks (say around a 1000) take a couple of seconds even a fast machine, and on Android/Termux, this can take a couple of minutes (!). Could the actual output could be cached? (And then `org-node-fakeroam--accelerate-get-contents` could optionally fetch the cached content.)

Figuring out when to recalculate the backlinks would be tricky though. (Though maybe at least for changes that org-node knows about this could be managed somewhat [things that changed in the background wouldn't be caught, but that's perhaps an acceptable cost].)

Using org-node on Android/Termux has addressed a lot of the issues that I've faced in terms of slow speed[0] of org-roam operations, but backlinks remain an issue.

[0]: I think it's all down to Android's use of some sort of FUSE overlay file system (even for the real internal storage). Whatever the exact cause for the slowness, it's definitely about file-system access and not raw processing or anything.

**Comment by meedstrom** [comment]
Interesting idea.  Yea, if the 1000 backlinks all come from different files... it'd have to get slow.  That's like running `org-node-backlink-fix-all` or equivalent until you reach the 1000th file.

**Comment by emacsomancer** [comment]
Ah, so you think the best way of "caching" would be just leaving the buffers open in the background? (I suppose this makes sense - the file system hits of actually accessing the files would occur if they're re-opened.)  I was initially thinking of just saving the output of the `*org-roam-buffer*` in a hash table linked to the source node - is there any way for that to work?

The dirty trick method: could the buffers be renamed with space preceding their names? As I recall, doing that prevents them from showing up by default in `ibuffer` or the like.

The other downside of doing the "dirty cache" method would be that it wouldn't help when Emacs is closed and re-opened. (If the hash table cache method is viable, that could be made persistent across sessions if the cache was saved out.)

**Comment by meedstrom** [comment]
Ah, hidden buffers, that would a good trick. Unfortunately Emacs has a [hard limit of 1024 open files](https://old.reddit.com/r/emacs/comments/1ebdbyy/opening_1024_files_in_one_loop_closing_each/), so it's really a no-go.

It does seem like `org-node-fakeroam--accelerate-get-contents` would be the place to do the caching.  A hash table that saves the result should work. I foresee that the main issue is when to renew a given result :) I suppose a table of mtimes should sort that out.

**Comment by emacsomancer** [comment]
For the renewal issue - what about a function added to either `org-node-insert-link` or (perhaps better) `org-node--handle-save` which modified the saved "backlinks result buffer" cache for that node if a link was added that referenced that node? (That wouldn't deal with changes that happened outside of the current Emacs session, so wouldn't help in the case of synced files that changed, for instance, of course.)

**Comment by meedstrom** [comment]
Worried it'll be slow even to check 1000 mtimes? I'll bet you one euro it's not :)

I've been wanting to simplify `org-node--try-launch-scan` by using a table of mtimes, so it's great that it can have a secondary purpose.

**Comment by emacsomancer** [comment]
I don't know. Just trying to do `find-file` on Termux in a directory with a lot of files takes forever (like over 10 seconds). But I'm not sure of the method of checking `mtimes`, so I'm not sure.

**Comment by meedstrom** [comment]
Yes, but you see, if those are Org files, I think you're seeing the slowness of turning on Org-mode in each visited buffer.  Try renaming them all to .txt and doing the same experiment!

**Comment by emacsomancer** [comment]
But I just mean the time between calling `find-file` and the minibuffer opening up with the interactive `find-file` component. Not actually opening any of the files (though that is sometimes slow too, and maybe that slowness is contribute to by the result of modes like Org-mode turning on).

**Comment by meedstrom** [comment]
Oh ok. That's probably filesystem indeed.

So let's see...

Guessing this takes over 10 seconds?

```elisp
(benchmark-run-compiled 1
  (directory-files-recursively
   (expand-file-name org-roam-dailies-directory
                     org-roam-directory)
   "."))
```

Then this takes... how long?

```elisp
(benchmark-run-compiled 10
  (let ((files
         (directory-files-recursively
          (expand-file-name org-roam-dailies-directory
                            org-roam-directory)
          ".")))
    (dolist (file files)
      (file-attribute-modification-time (file-attributes file)))))
```

Second form takes my machine 20x longer than the first form.  So be prepared :)

**Comment by emacsomancer** [comment]
The first results in: 

`(11.620225429000001 0 0.0)`

**Comment by emacsomancer** [comment]
The second seems to be roughly the same: 

`(10.338752852999999 0 0.0)`

**Comment by meedstrom** [comment]
Filesystems man...

Btw you spoke of general sluggishness. I'm guessing with a lot of things in Emacs. But also that `M-x org-node-reset` blocks Emacs for 6-11 seconds before it even starts scanning? And this is not shown in the time elapsed message at the end.

Alas, using a memoized result in that case would not be sane. Maybe the work of `org-node-files` should be carried out in an external process :p

I saw in one of the printouts on #17, that you have `org-node-perf-max-jobs` automatically set to 1 on some of your devices?  There could be room to improve `org-node--count-logical-cores`.

**Comment by emacsomancer** [comment]
Yes, I count 17 seconds for `M-x org-node-reset` on Android/Termux. 

Why would using the memoised result then not be sane? Why would it require doing `org-node-reset` frequently?

I haven't manually touched `org-node-perf-max-jobs` anywhere, and both my one laptop and my phone report `7` for this variable. (Unless it's somewhere getting reset temporarily by something else??)

**Comment by meedstrom** [comment]
Ah. My bad then, I assumed too much about the printout.  The 1 in the line

      org-node--handle-finished-job(1 org-node--finalize-modified)

is just because there was only one file to scan.  All good.

**Comment by meedstrom** [comment]
> Why would using the memoised result then not be sane? Why would it require doing `org-node-reset` frequently?

In short, `(org-node--scan-all)` is where the magic happens whereby it finds IDs, new files, deleted files.   Wouldn't be able to do that if it used a cached file list :)

The issue I foresee is that on your Termux setup `org-node--maybe-adjust-idle-timer` might get too optimistic.  It sets an idle timer for this many seconds: `(* 25 (1+ org-node--time-elapsed))`. That would be fine if `org-node--time-elapsed` returns 17 seconds, stretching the idle timer to over 7 minutes.  But I guess it actually returns 1 second or so?  Then the timer will run after only 50 idle seconds, which then blocks Emacs for 17 seconds, long enough that you might notice it hung sometimes when you get back to the device...

**Comment by emacsomancer** [comment]
`org-node--time-elapsed` returns 7.740299321, so nearly 8 seconds.

I haven't noticed it hung at all when I come back to a session.

**Comment by meedstrom** [comment]
Ok, just committed a version that will cache the contents! Let me know if it helped!

**Comment by emacsomancer** [comment]
do I have to enable anything?

**Comment by meedstrom** [comment]
Naw.

**Comment by emacsomancer** [comment]
I've got (essentially Option 1c):

````
  (setq org-roam-db-update-on-save nil) ;; don't update DB on save, not needed
  (setq org-roam-link-auto-replace nil) ;; don't look for "roam:" links on save

(org-node-cache-mode)
  
  (setq org-node-alter-candidates t)
  
  (setq org-node-creation-fn #'org-node-new-via-roam-capture)
  (setq org-node-slug-fn #'org-node-slugify-like-roam-actual)
  (setq org-node-datestamp-format "%Y%m%d%H%M%S-")
  ;; end 0.4 things
  (setq org-node-creation-hook nil)
  (setq org-node-extra-id-dirs (list org-roam-directory))


  (org-roam-db-autosync-mode 0)
  (org-node-fakeroam-nosql-mode)
  (org-node-fakeroam-redisplay-mode)
````

But updating to the latest doesn't seem to make any difference with respect to backlinks, either on regular desktop or on Android/Termux. If I have the *org-roam* buffer open, opening file node with many backlinks [300-800] is still slow (a couple of seconds on desktop and 15-30 on mobile), and even for nodes I've opened before, it's the same amount slow if I switch back to them (having switched to a different one and having had the *org-roam* shift).

**Comment by meedstrom** [comment]
The table `org-node--file<>previews` is not empty, right?

**Comment by emacsomancer** [comment]
No, it's full of things.

**Comment by meedstrom** [comment]
When I edebug `org-node-fakeroam--accelerate-get-contents` and revisit some node, I see it is retrieving the cached strings instead of visiting the files anew.

Maybe it is slow for a different reason?  Maybe you can start the profiler and visit some node so the Roam buffer populates, then do `M-x profiler-stop` and `M-x profiler-report`.

**Comment by meedstrom** [comment]
One thing sticks out in my profiler: it runs `org-roam-fontify-like-in-org-mode` on the cached string, which creates a temp buffer and enables org-mode in that buffer :)  Seems pretty unnecessary...

**Comment by emacsomancer** [comment]
> One thing sticks out in my profiler: it runs `org-roam-fontify-like-in-org-mode` on the cached string, which creates a temp buffer and enables org-mode in that buffer :) Seems pretty unnecessary...

Yes, just running it and that sticks out to me too. (Also, in mine, maybe additionally applying visual-fill-column mode (which also is unnecessary.)

**Comment by meedstrom** [comment]
Rudimentary fix, but now the content previews are not fontified.

```elisp
(defun org-node-fakeroam--accelerate-get-contents (orig-fn file pt)
  "Designed as around-advice for `org-roam-preview-get-contents'.

Normally the first time you open an org-roam-buffer, Emacs hangs
for as long as a minute on a slow machine when huge files are
involved.  This may eliminate most of that.

Aside from huge files, it is also slow when there are backlinks
from extremely many files.  This caches all results so that
should only be slow the first time each backlink is visited."
  (let* ((cached (alist-get pt (gethash file org-node--file<>previews)))
         (result (or cached
                     ;; TODO: User-configurable let-bindings here
                     (let ((org-inhibit-startup t))
                       (org-roam-fontify-like-in-org-mode
                        (funcall orig-fn file pt))))))
    (unless cached
      (push (cons pt result)
            (gethash file org-node--file<>previews)))
    result))

(advice-add #'org-roam-node-insert-section :around
            (defun run-without-fontifying-again (fn &rest args)
              (cl-letf (((symbol-function 'org-roam-fontify-like-in-org-mode)
                         #'identity))
                (apply fn args))))
```

**Comment by emacsomancer** [comment]
> One thing sticks out in my profiler: it runs `org-roam-fontify-like-in-org-mode` on the cached string, which creates a temp buffer and enables org-mode in that buffer :) Seems pretty unnecessary...

If I alter `org-roam-node-insert-section` and comment out the `org-roam-fontify-like-in-org-mode` it's vastly improved performance.

**Comment by emacsomancer** [comment]
> Rudimentary fix, but now the content previews are not fontified. I was hoping the fontification would stay in the cached strings.
> 
> ```emacs-lisp
> (defun org-node-fakeroam--accelerate-get-contents (orig-fn file pt)
>   "Designed as around-advice for `org-roam-preview-get-contents'.
> 
> Normally the first time you open an org-roam-buffer, Emacs hangs
> for as long as a minute on a slow machine when huge files are
> involved.  This may eliminate most of that.
> 
> Aside from huge files, it is also slow when there are backlinks
> from extremely many files.  This caches all results so that
> should only be slow the first time each backlink is visited."
>   (let* ((cached (alist-get pt (gethash file org-node--file<>previews)))
>          (result (or cached
>                      (let ((org-inhibit-startup t))
>                        (org-roam-fontify-like-in-org-mode
>                         (funcall orig-fn file pt))))))
>     (unless cached
>       (push (cons pt result)
>             (gethash file org-node--file<>previews)))
>     result))
> 
> (advice-add #'org-roam-node-insert-section :around
>             (defun run-without-fontifying-again (fn &rest args)
>               (cl-letf (((symbol-function 'org-roam-fontify-like-in-org-mode)
>                          #'identity))
>                 (apply fn args))))
> ```

Ah! I'll try this.

**Comment by meedstrom** [comment]
Oh, I think I shot myself in the foot with the `cl-letf`. Of course it would just call `identity` even in the accelerate-get-contents function :)

**Comment by meedstrom** [comment]
Below version calls org-fontify-like-in-org-mode instead of org-roam-fontify-like-in-org-mode.  Then it fontifies correctly.

```elisp
(defun org-node-fakeroam--accelerate-get-contents (orig-fn file pt)
  "Designed as around-advice for `org-roam-preview-get-contents'.

Normally the first time you open an org-roam-buffer, Emacs hangs
for as long as a minute on a slow machine when huge files are
involved.  This may eliminate most of that.

Aside from huge files, it is also slow when there are backlinks
from extremely many files.  This caches all results so that
should only be slow the first time each backlink is visited."
  (let* ((cached (alist-get pt (gethash file org-node--file<>previews)))
         (result (or cached
                     (let ((org-inhibit-startup t))
                       (org-fontify-like-in-org-mode
                        (funcall orig-fn file pt))))))
    (unless cached
      (push (cons pt result)
            (gethash file org-node--file<>previews)))
    result))
```

**Comment by meedstrom** [comment]
Committed to both main and dev.

**Comment by meedstrom** [comment]
> One issue I've run into is that some things mess up the construction of the buffers (a node changed its filename and org-node doesn't yet know about the name change; some sort of font-locking or other issue occurs) and these things mean that the buffer is never entirely constructed and so (I think; still testing things) it ends up being rebuilt (or attempted to be rebuilt) the next time that node's backlinks are open(ed).

Hum.  Well, `org-node--file<>previews` keys on the filename, so indeed it would have to re-cache some context previews.  It wouldn't need to do it for a whole roam buffer, just the backlinks from the files that changed. I think that renames are rare enough that this is not a big deal.

Not sure what's going on in the issue you describe.  But a filename change should be picked up pretty fast due to `org-node--handle-save` ... admittely it's async, so not instant.

**Comment by emacsomancer** [comment]
> > One issue I've run into is that some things mess up the construction of the buffers (a node changed its filename and org-node doesn't yet know about the name change; some sort of font-locking or other issue occurs) and these things mean that the buffer is never entirely constructed and so (I think; still testing things) it ends up being rebuilt (or attempted to be rebuilt) the next time that node's backlinks are open(ed).
> 
> Hum. Well, `org-node--file<>previews` keys on the filename, so indeed it would have to re-cache some context previews. It wouldn't need to do it for a whole roam buffer, just the backlinks from the files that changed. I think that renames are rare enough that this is not a big deal.
> 
> Not sure what's going on in the issue you describe. But a filename change should be picked up pretty fast due to `org-node--handle-save` ... admittely it's async, so not instant.

I'll experiment (by just using it) more and see what things may occur. (I think the background hook for updating may just be somehow never running for me on mobile? I'm not sure. Something else to check.) The filename change thing seems to be an issue where the filename change happened in a different Emacs session.

What do you think of (optionally) saving out `org-node--file<>previews` to a file and (optionally) reading it back in when a new Emacs session is started?

**Comment by meedstrom** [comment]
> What do you think of (optionally) saving out org-node--file<>previews to a file and (optionally) reading it back in when a new Emacs session is started?

Hm! It's actually pretty simple to do if you have savehist-mode.

```elisp
(add-to-list 'savehist-additional-variables 'org-node--file<>previews)
(add-to-list 'savehist-additional-variables 'org-node--file<>mtime)
```

I'll test this over the next days.

**Comment by emacsomancer** [comment]
Ah, this is an excellent solution (using an existing thing)!

**Comment by meedstrom** [comment]
My savehist-file was around 600 kB before this, now I suppose it could grow to a few MB. But that's only terrible if some other package is accesses the savehist-file in an inefficient way.  I'll await bug reports then write a report upstream to the violating package. ;-)

**Comment by meedstrom** [comment]
Now using persist instead of savehist.

**Comment by meedstrom** [comment]
@emacsomancer  I've realized there is a potential privacy issue with syncing this stuff to disk.  So now I'm leaning towards removing the persistence.  My impression is it would quite rarely matter anyway.

I happened to write some code to migrate the persistence setup to the fakeroam codebase, which I'll not do after all, but you could copy-paste this into initfiles if you want. Untested, but I'm pretty confident it'll work :)

```elisp
(require 'persist)
(persist-defvar org-node-fakeroam--saved-previews nil nil)
(persist-defvar org-node-fakeroam--saved-mtimes nil nil)
(defvar org-node-fakeroam--persist-timer (timer-create))

(defun org-node-fakeroam--persist-previews ()
  "Sync cached previews to disk."
  (setq org-node-fakeroam--saved-previews org-node--file<>previews)
  (setq org-node-fakeroam--saved-mtimes org-node--file<>mtime)
  (persist-save 'org-node-fakeroam--saved-previews)
  (persist-save 'org-node-fakeroam--saved-mtimes))

(defun my-setup-persist ()
  "If there is cached data, load it, then reset main org-node cache
to ensure everything is sane."
  (when org-node-fakeroam--saved-previews
    (setq org-node--file<>previews org-node-fakeroam--saved-previews))
  (when org-node-fakeroam--saved-mtimes
    (setq org-node--file<>mtime org-node-fakeroam--saved-mtimes)
    (org-node-cache-ensure nil t))
  (cancel-timer org-node-fakeroam--persist-timer)
  (setq org-node-fakeroam--persist-timer
        (run-with-idle-timer 60 t #'org-node-fakeroam--persist-previews)))

(add-hook 'org-node-fakeroam-fast-render-mode-hook #'my-setup-persist)
```

**Comment by emacsomancer** [comment]
I think it does make a difference on Android/Termux, because every time of hitting the file system is costly, and so for backlinks, especially where there are lots of them.

I don't understand the privacy issue. What is the scenario you have in mind? Surely the cache doesn't really contain any additional information that's not already present on disk, since the note org files themselves will be on disk. where would the issue arise?

[You don't think this could continue to be a possible feature of org-node, especially if, for instance, it was disabled by default?]

**Comment by meedstrom** [comment]
I suppose it can be in fakeroam, disabled by default.  Merged more or less the snippet above, so your initfiles can have just:

     (org-node-fakeroam-enable-persist)

> What is the scenario you have in mind?

The persisted previews would go in .emacs.d, which could have different filesystem permissions than where the notes are located.

**Comment by emacsomancer** [comment]
Thank you - I realise my use case may be an edge case, and I appreciate it.

I see what you mean for the privacy issue now. Does "persist.el" have any latitude for storing/retrieving things from a location other than .emacs.d, I wonder.

**Comment by meedstrom** [comment]
No problem, I appreciate the bug reports you have made.

BTW. Did you know that Elpaca inherits keywords from the Melpa recipe (https://github.com/melpa/melpa/blob/master/recipes/org-node-fakeroam)?  So if you have `(elpaca org-node)` it will actually install the "melpa" branch and not the "main" branch.  That could be good to know ;) I'll push to both branches now anyway.

**Comment by emacsomancer** [comment]
I've just been continuing to use elpaca to fetch org-node thing directly by the github repo, e.g.

```` elisp
(use-package org-node
  :ensure (:host github :repo "meedstrom/org-node")
....
````

**Comment by meedstrom** [comment]
Yes or `:inherit nil`.  But the melpa branch is good too, I keep it a bit more stable than main and it's rarely far behind.

**Comment by meedstrom** [comment]
Now the MELPA recipe points at "main".

**Comment by meedstrom** [comment]
Refactored it a bit now in https://github.com/meedstrom/org-node-fakeroam/commit/e6680d899167eceb516f40009cb8c52814b364e2 so it does not need to de-cache previews so often. Now mo cached previews are preserved even if you are working in one huge file and all the backlinks come from that same file (previously, everything from the file got wiped when the file was saved).

**Comment by emacsomancer** [comment]
Well, I hadn't used it in a while, and Android is updated in the meantime, and now some things are broken; it took quite a while to get into a vaguely workable state (jinx module won't compile anymore, etc.) and I'm using quelpa there rather than elpaca as it felt lighter, but I'm not used to it.

Anyway, Think I've got it running. The initial lookup seems slow (any way to cache that optionally from last session?), but then it seems fast after that. (Opening files can be a bit slow, but that's the Android FUSE stuff again.)

Anything in particular I should test?

**Comment by meedstrom** [comment]
Good that it still seems to work. I recently got a Hannsnote2 (Android 13), so once I sync some initfiles I can test it too :)

**Comment by emacsomancer** [comment]
The FUSE mounting issue is the main one with Android, I think, - and this isn't org-node specific. Navigate to a directory with a 1000+ files in it and it'll hang noticeably. (See https://source.android.com/docs/core/storage/fuse-passthrough#fuse-versus-sdcardfs - but I don't understand why it's *so* bad on Android, the docs reference issues for low-to-medium-end devices; but I've got a high-end device from Google themselves 😕 .)

**Comment by meedstrom** [comment]
I don't suppose the slow mounts are under `/content/storage`? I guess not, just checking.

> The third is storage provided by other applications (Nextcloud, for
> example) through the Storage Access Framework--this storage is
> extremely slow (thanks in part to Google's botched implementation of
> document provider IPC), and is located within subdirectories of
> /content/storage.

--- https://sourceforge.net/projects/android-ports-for-gnu-emacs/files/

In other news, I'm having to declare Emacs bankruptcy because my initfiles make this device too slow :) 

not to mention that so many hotkeys don't work... hate coming up with new hotkeys

**Comment by emacsomancer** [comment]
I don't think so, they're symlinks in Termux's file system which point to `/storage/emulated/0`, as far as I know. ...unless those end up themselves mounted on `/content/storage` in the back-end???

> In other news, I'm having to declare Emacs bankruptcy because my initfiles make this device too slow :)

Yeah, now you maybe guess why my Android init.el is different from my desktop one.... (and things continually break... jinx won't compile right under termux anymore, etc.)

> not to mention that so many hotkeys don't work... hate coming up with new hotkeys

in case it's of help - maybe see https://babbagefiles.xyz/termux-extra-keys-emacs-org-roam-node-android/ as a model

**Comment by meedstrom** [comment]
Thanks for the link! I'd seen it before but forgotten. Some very handy tips in there. 

Though for now I hope to not need the onscreen keyboard at all, nor Termux extra keys.  Trying to make the Bluetooth keyboard work with less input latency.  Got this Hannsnote2 (an [RLCD](https://old.reddit.com/r/Reflective_LCD/comments/1p11agb/rlcd_and_tlcd_tablets_and_monitors/) tablet) for precisely that reason.

Starting to think that the Hannsnote2 may need a USB-C hub for some RF wireless peripherals instead, because its Bluetooth seems terrible. The typing lag is not worse than e-ink, but nor is it often much better. Seems to vary a lot with interference from other radio devices. Or I'm just doing something weird. Should write a blog post like yours once I pin it all down :)

Did you notice that C-M- hotkeys don't seem to work in Termux? It works in the native Emacs app tho!

**Comment by meedstrom** [comment]
> (and things continually break... jinx won't compile right under termux anymore, etc.)

Ever gave Andronix or UserLAnd a spin, instead of Termux? Tho I understand that Termux's adaptations to touch are quite nice if you plan to use touch.
