### ISSUE TITLE
rename function renaming dailies

### ISSUE THREAD

**Issue by emacsomancer** [meedstrom/org-node#30]
After the changes, the rename function tries to rename dailies.

**Comment by meedstrom** [comment]
Forgot to say. Check out the setting `org-node-renames-exclude`.  Sorry about that.

**Comment by emacsomancer** [comment]
My dailies are in a subfolder of `org-roam` named `daily`, but they still get renamed by the hook. I tried even providing the variable the full path, but it still renames them (wrongly, thinking that they're non-dailies).

**Comment by meedstrom** [comment]
What does this return in your daily file?

    M-: (string-match-p "daily/" buffer-file-name)

**Comment by emacsomancer** [comment]
35

**Comment by meedstrom** [comment]
Sorry for the delay, I waited out the GitHub outage just now.

Well, it should work, since that filter returns non-nil. I don't know what's going on. It works for me.   You don't have the function defined to something else? :)

**Comment by emacsomancer** [comment]
I'm guessing it's an issue with `org-node-renames-allowed-dirs`.

I'm thinking that in:

````
              (cl-loop
               for dir in org-node-renames-allowed-dirs
               if (or (not (string-prefix-p dir path))
                      (string-match-p org-node-renames-exclude path))
               return nil
               finally return t)
````

the loop returns returns true if `org-node-renames-allowed-dirs` is empty. 

maybe

````
  (when (null org-node-renames-allowed-dirs)
        (message "New user option `org-node-renames-allowed-dirs' should be configured"))
````

should be `user-error` instead of `message`?

**Comment by meedstrom** [comment]
>  the loop returns returns true if org-node-renames-allowed-dirs is empty. 

Oh, well spotted. It was too confusingly written. I changed the loop so it's more readable and won't do that.

**Comment by meedstrom** [comment]
Oh, yes, probably.

**Comment by meedstrom** [comment]
Heads up just in case: just edited this command fairly extensively, but it still works in my testing.
