### ISSUE TITLE
rename hook now renaming all files

### ISSUE THREAD

**Issue by emacsomancer** [meedstrom/org-node#38]
the rename hook now seems to try to rename files (not dailies, those are fine,  but non-dailies) even when their name hasn't changed.

**Comment by emacsomancer** [comment]
Yes, I'll have to look at it. I added to my config some auto-save-visited and auto-git-commit things; I wonder if they affect anything.

**Comment by meedstrom** [comment]
Re-dating the files is a major problem!  So I tried it with a non-blank datestamp format and looks like I'm getting the issue too :)

**Comment by meedstrom** [comment]
Fixed.
