### ISSUE TITLE
Rewrite headlines

### ISSUE THREAD

**Issue by Ypot** [meedstrom/org-node#4]
org-node-rewrite-links-ask seems a nice feature I have been needing long ago.
But it doesn't seem to work.
let: Symbol’s function definition is void: org-with-file-buffer

**Comment by meedstrom** [comment]
I'm surprised to see that. I had the same issue because `org-macs` was not loaded at compile-time, but it should be now since it is required in org-node-lib.el.

What happens if you visit org-node.el (`M-x find-library RET org-node RET`), do M-x eval-buffer, then try the command again?
