### ISSUE TITLE
Typo in org-node.el

### ISSUE THREAD

**Issue by CRTandKDU** [meedstrom/org-node#41]
In the function: `org-node-insert-link`
https://github.com/meedstrom/org-node/blob/42fad777df8238679feda63880e3cd70382a97f9/org-node.el#L2607

shouldn't 
`
         (input (completing-read "Node: " #'org-node-collection
                                 () () initial 'org-noden-hist))
`

at line `2607 ` read
`
         (input (completing-read "Node: " #'org-node-collection
                                 () () initial 'org-node-hist))
`
instead?

Best Regards,
CRTandKDU

**Comment by meedstrom** [comment]
Thanks!
