### ISSUE TITLE
Prefixes in `org-node-abbrev-file-names`

### ISSUE THREAD

**Issue by CRTandKDU** [meedstrom/org-node#42]
Hello, 
When running on Windows, the function `org-node-abbrev-file-names` at:
https://github.com/meedstrom/org-node/blob/9d84174174516e3229deaed70570fe7399e035e0/org-node.el#L1606
might occasionally choke when full file names include the drive specification as in `c:/file.org`. 

In my installation I changed the prefix test to:

```
                  do (if (string-prefix-p
			   (if (eq system-type 'windows-nt) "c:/" "/")
			   path)
                          (setq path (directory-abbrev-apply path))
                        (error "Not true or absolute filename: %s" path))
```
 which works fine.

But this is an incomplete patch, as it hard-codes the drive letter. There is certainly a cleaner way in Elisp to test for the presence of a drive letter in the full file/directory name -- I'll have to look into it!

Best,
CRTandKDU

**Comment by meedstrom** [comment]
Hm. Maybe we can just eliminate it.

                       do (setq path (directory-abbrev-apply path))

**Comment by meedstrom** [comment]
Pushed in [8612989](https://github.com/meedstrom/org-node/commit/8612989f1af76aa48413242b51780078caea9e8f).  Let me know if there are other issues that follow.

**Comment by CRTandKDU** [comment]
Well, the drive letter also shows after the `directory-abbrev-apply` --  I don't know whether it matters further down.

The Elisp manual seems to say that under MS-DOS (by extension Windows?), drive letters may or may not be required...


Anyhow I came up with this to factor away the drive letter if needed:

```
(defun drive-letter-p (filename)
  (string-suffix-p
   ":"
   (car (file-name-split (file-name-directory filename)))))
```

which returns `t` if the filename starts with a drive letter.  

Accordingly we can then test prefix either on `/` or `(concat (car (file-name-split (file-name-directory deft-directory))) "/"), ` or something similar. More compact:

```
(defun which-prefix (filename)
  (let ((dir (car (file-name-split (file-name-directory filename)))))
    (if (string-suffix-p ":" dir) (concat dir "/") "/")))
```

This also worked fine for me.
Best,
CTRandKDU
