### ISSUE TITLE
org-node-find issue?

### ISSUE THREAD

**Issue by emacsomancer** [meedstrom/org-node#44]
Latest update, I get an error with `org-node-find`:

```` elisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-directory(nil)
  org-node-changes--warn-and-copy()
  org-node-cache-ensure()
  org-node-find()
  funcall-interactively(org-node-find)
  command-execute(org-node-find)
````

I assume this is org-node not finding my org-roam main directory?

**Comment by meedstrom** [comment]
Sorry, I'll look into it now. Been shuffling code around bc fakeroam finally made it to MELPA!

**Comment by emacsomancer** [comment]
If I'm using devel via elpaca, do I need to add the "fakeroam" things as a separate "use-package" declaration?
