### ISSUE TITLE
org-node--series-goto-previous 

### ISSUE THREAD

**Issue by emacsomancer** [meedstrom/org-node#45]
Is there an off-by-one issue here somehow? For some reason doing `(org-node--series-goto-previous "d")` doesn't work anymore. It doesn't error or complain, but it just stays on the current day.

**Comment by meedstrom** [comment]
Sorry about all these fires to put out. You're a very patient contributor!

**Comment by meedstrom** [comment]
To clarify, goto-next worked?

I found that my `(org-node--guess-daily-dir)` was guessing the directory wrong so long as the module `org-roam-dailies` had not been loaded, so my daily series did not work at all.  After the recent fix, the series works for me, both previous and next.

**Comment by emacsomancer** [comment]
Thanks, Martin!

The behaviour I was getting was (haven't tested the latest commit yet):

1) goto-next worked as expected
2) goto-prev worked when and only when the current daily was nascent and not if it was actual(/in the org-node hash table)

**Comment by meedstrom** [comment]
OK, that's good info!  Some ideas

- Maybe the `:whereami` lambda may not be returning a string in the form that matches what `:classifier` would have generated. I'll think about whether that case would be handled correctly.
- Maybe it works for me because I use `(setq org-node-creation-fn #'org-node-new-file)`.  Because the hook `org-node-creation-hook` should call `#'org-node--add-series-item`, and the fakeroam creator does temporarily add the same function to Roam's `org-roam-capture-new-node-hook`, but maybe it is the wrong hook to put it on.

**Comment by emacsomancer** [comment]
Hmm.. the latest commit seems to still behave in the same way I described. I'll try to working on testing/debugging later today.

**Comment by meedstrom** [comment]
Refactored goto-next/goto-previous, might help.

**Comment by emacsomancer** [comment]
Still same behaviour after update. Still have a suspicion of something like an off-by-one issue (given the behaviour: (a) it working when the current daily is nascent; (b) the fact that goto-next work), but haven't had time to test this theory, dig into the code, &c.

**Comment by meedstrom** [comment]
What's the output of evalling this in a daily buffer?

    (let ((series (cdr (assoc "d" org-node--series))))
      (funcall (plist-get series :whereami))))

And does that have a corresponding entry in the org-node--series variable?

**Comment by emacsomancer** [comment]
a string of the title/date of the daily. e.g. today's returns `"2024-09-17"`.

**Comment by emacsomancer** [comment]
Ah, ah. I see the issue. When I look at the `org-node--series` variable, all the extant dailies are doubled for some reason:

```` elisp
 ....
  :key "d" :sorted-items
  (("2024-09-17" . "~/Documents/Org/org-roam/daily/2024-09-17.org")
   ("2024-09-17" . "~/Documents/Org/org-roam/daily/2024-09-17.org")
   ("2024-09-16" . "~/Documents/Org/org-roam/daily/2024-09-16.org")
   ("2024-09-16" . "~/Documents/Org/org-roam/daily/2024-09-16.org")
   ("2024-09-15" . "~/Documents/Org/org-roam/daily/2024-09-15.org")
   ("2024-09-15" . "~/Documents/Org/org-roam/daily/2024-09-15.org")
   ("2024-09-15" . "~/Documents/Org/org-roam/daily/2024-09-15.org")
   ("2024-09-15" . "~/Documents/Org/org-roam/daily/2024-09-15.org")
   ("2024-09-15" . "~/Documents/Org/org-roam/daily/2024-09-15.org")
   ("2024-09-15" . "~/Documents/Org/org-roam/daily/2024-09-15.org")
....
````

**Comment by meedstrom** [comment]
Alright, I used to have `org-node--build-series` de-dup the list. That would work around this issue. I removed the de-dupping not long ago to try to squeeze perf, but it probably should de-dup.

E.g. because you could have two ID nodes in the same file. Yup, I'll add it back in.

**Comment by meedstrom** [comment]
The change was actually part of a change so that one run of :classifier can return a *list* of items, so I'll have to implement it a bit different this time.  Just trying to eke out a performant way :)

Would be nice if the classifiers could somehow be guaranteed not to return duplicates in the first place.  Or maybe the de-dup just happens a little later.

**Comment by meedstrom** [comment]
```elisp
(defun org-node--series-dedup ()
  (cl-loop for series in org-node--series
           do (delete-dups (plist-get series :sorted-items)))
```

That work for you?

**Comment by meedstrom** [comment]
My bad, that was wrong.  This seems to work:

```elisp
(dolist (series org-node--series)
  (delete-consecutive-dups (plist-get (cdr series) :sorted-items)))
```

**Comment by emacsomancer** [comment]
> ```emacs-lisp
>   (cl-loop for series in org-node--series
>            do (delete-consecutive-dups (plist-get series :sorted-items)))
> ```
> 
> That work for you?

Yes. Once I run that, goto-prev works as expected.

**Comment by emacsomancer** [comment]
> My bad, that was wrong. This seems to work:
> 
> ```emacs-lisp
> (dolist (series org-node--series)
>   (delete-consecutive-dups (plist-get (cdr series) :sorted-items)))
> ```


Yes. Once I run that, goto-prev works as expected.
