### ISSUE TITLE
Is there an analog to org-roam-node-display-template?

### ISSUE THREAD

**Issue by Artawower** [meedstrom/org-node#47]
Hi, thanks for your package, it really is incredibly fast! I tried to find a `org-roam-node-display-template` counterpart via the customize menu, but without success. Can you please tell me if there is such functionality?

I prefer to search by tags rather than by name, and through such a function it's very easy to mix these approaches. In addition, it allows me to display exactly the view for which it is easiest for me to search for information. Or is there some other way to achieve this look?

<img width="794" alt="47810" src="https://github.com/user-attachments/assets/09d63a91-11cb-468a-a9eb-9a1c7a75b4e4">

**Comment by meedstrom** [comment]
Hi, I'm glad you enjoy it! 

This can actually be done through the very first option, `org-node-affixation-fn`.  Maybe I'll add a tip to the readme.  Check the source of the function `org-node-affix-with-olp` for how to write a new one.  Maybe something like this:

```elisp
(setq org-node-affixation-fn
      (defun my-prefix-with-tag (node title)
        "Let NODE's tags prefix TITLE."
        (list title
              (when-let ((tags (org-node-get-tags node)))
                (propertize (concat "(" (string-join tags ", ") ") ")
                            'face 'completions-annotations))
              nil)))
```

Then do a `M-x org-node-reset` and see if you like the result.

You can change which face is applied, by switching the `'completions-annotations` for some other face.

And to match against these annotations, you can either set `org-node-alter-candidates` to t, or use some completion framework like Orderless which have tricks to let you match against annotations in any command.  Maybe this option should be renamed for clarity, but I'm not sure to what.

**Comment by Artawower** [comment]
Thank you so much! This is just what I was looking for
