### ISSUE TITLE
Detail in README the behavior of org-node-backlink-fix-whole-buffer 

### ISSUE THREAD

**Issue by hpgisler** [meedstrom/org-node#49]
Setup: Let the content of a heading A without an `:ID:` link to a heading B which has an `:ID:` (obviously).
Then call `org-node-backlink-fix-whole-buffer`, the property `:BACKLINK:` in B will be assigned (or generated) the `:ID:` of the file in which A is contained, rather then to a newly generated `:ID:` in A.

This behavior makes perfectly sense - in my opinion.

However, I did not expect it and somehow assumed, that the  missing `:ID:` inside heading A would be auto-generated, rather then in the file. It would be good, if the current behavior would be documented.

**Comment by meedstrom** [comment]
Would a blurb like this work? 

"To be clear, this never generates new IDs.  That's your own business.  No backlink will ever appear, if there is no ID among the outline ancestors where the link was found."

**Comment by meedstrom** [comment]
Thanks :)
