### ISSUE TITLE
'<filename>:<lineno> (error Possibly malformed property drawer)' for parsed org-agenda archive files

### ISSUE THREAD

**Issue by nrvale0** [meedstrom/org-node#51]
# config
```
(use-package org-node
    :after org
    :config
    (org-node-cache-mode)
    (setq org-node-extra-id-dirs "~/Org"))

  (use-package org-node-fakeroam
              :defer)
```

org-agenda archive files are located in ~/Org also and when org-node is parsing them it gets upset with the contents of :PROPERTIES: of archived org-agenda entries. The output of `org-node-scan-list-problems` just says:

    <filename>:<lineno> (error Possibly malformed property drawer)

I've set debug toggle but the scan does not produce errors and thus I'm not able to get a breakpoint to inspect where things are off the rails.

thx

**Comment by meedstrom** [comment]
Thanks for the report! Can you show me how those archived entries look?

**Comment by meedstrom** [comment]
FYI: 

     (setq org-node-extra-id-dirs "~/Org")

should be

    (setq org-node-extra-id-dirs '("~/Org"))
