### ISSUE TITLE
org-id-locations-file-relative must be nil

### ISSUE THREAD

**Issue by fleimgruber** [meedstrom/org-node#52]
This currently blocks me from trying org-node:

https://github.com/meedstrom/org-node/blob/2a607f6ab80007bcb63933c648d390304ac424ee/org-node.el#L827

as I am using my Emacs config on multiple machines and OSes.

I tried to figure it out, but I can't see the reason for it, just curious.

Could this requirement be relaxed?

**Comment by meedstrom** [comment]
I guess it would be good to relax the requirement in any case.  It may take a while, since various functions like `org-node--forget-id-locations` currently assume absolute names, but I'll ping you when ready.

**Comment by fleimgruber** [comment]
Thanks for checking back (and so fast)!

I don't understand what you mean by device-specific path. Right now, org-id-locations-file is in ~/repo where repo is a git repo that is "synced" across machines using git. All org files are in there, so all relative paths are effectively absolute paths with that dir as the root.

To your second paragraph: The relative paths help in my case because e.g. on Windows it's C\Users\user\repo and on *nix it's /home/user/repo. Am I missing something?

I guess my use-case is special here as my setup guarantees that all org files share a known root?

**Comment by fleimgruber** [comment]
> I guess it would be good to relax the requirement in any case. It may take a while, since various functions like `org-node--forget-id-locations` currently assume absolute names, but I'll ping you when ready.

Thanks for considering! I am happy to help test this for my use-case, but I can totally understand if it's a bigger change and needs more time and consideration.

**Comment by meedstrom** [comment]
> I don't understand what you mean by "device-specific path". 

On second thought, my idea would amount to basically

```elisp
(setq org-id-locations-file (file-name-concat temporary-file-directory "org-id-locations"))
(setq org-node-extra-id-dirs (list "~/repo"))
```

That has the small drawback that your devices won't remember any IDs that happen to be seen outside ~/repo.

**Comment by fleimgruber** [comment]
This is similar to what I have already:
```
(setq org-id-locations-file "abs/path/to/repo/org-id-locations"))
(setq org-node-extra-id-dirs (list "~/repo"))
```
where "abs/path/to/repo" is per-device, but always in "home" ~/repo. The reason I set the offending org-id-locations-file-relative to `t` is so that those per-device paths do not end up in org-id-locations-file (IIUC). From it's docstring: "This customization is useful when folders are shared across systems but mounted at different roots.  Relative path to org-id-locations-file still has to be maintained across systems."

> That has the small drawback that your devices won't remember any IDs that happen to be seen outside ~/repo.

This won't happen in my case due to "all org files share a known root" which is "~/repo".

**Comment by meedstrom** [comment]
If I understand you, "abs/path/to/repo/org-id-locations" leads to a location inside of the git repo that you sync across devices, yes?

My proposal would place it in /tmp.  That way, each device generates their own, temporary, org-id-locations file, in their own /tmp (or whatever is the Windows equivalent).

With that done, you could set

```elisp
(setq org-id-locations-file-relative nil)
```

and org-node should work as expected.

**Comment by fleimgruber** [comment]
Works for me, off to `org-roam-node-display-template`...

**Comment by meedstrom** [comment]
I've now removed the error message, since I believe it will work anyway. I misunderstood the docstring - it sounded like it would always use relative filenames, but in actuality it just transforms them to relative when syncing to disk with `org-id-locations-save`, but the in-memory values in `org-id-locations` variable are still absolute :)
