### ISSUE TITLE
Best Practice Question: Best form of node headings?

### ISSUE THREAD

**Issue by hpgisler** [meedstrom/org-node#53]
After playing around a bit and getting the feel of the package, I note following:

- Having quite a lot of nodes (headings with `:ID:` property) 
- Having set `org-node-complete-at-point-mode` to `t`
- Most headings containing both: relevant key words (usually nouns), and irrelevant filles, such as 'is', 'the', etc.

Now whin typing away in some buffer (of course) also the 'fillers' trigger auto-complete proposals - which of course usually do not make a lot of sense.

How do you handle this effect? Any best practices?

**Comment by meedstrom** [comment]
I exoerience similar, heh. I don't use the mode but @cashpw or someone else who does might have some insights.

**Comment by cashpw** [comment]
You can look at my personal configuration (config-personal.org in my dotfile repo) for specifics. I had the same problem that you're describing. I set the autocomplete timer to half a second in order to have false positives occur less frequently but they still happen from time to time.

**Comment by hpgisler** [comment]
> You can look at my personal configuration (config-personal.org in my dotfile repo) for specifics. I had the same problem that you're describing. I set the autocomplete timer to half a second in order to have false positives occur less frequently but they still happen from time to time.

Sorry for my ignorance: which section do you refer to?:
https://github.com/cashpw/dotfiles/blob/main/config/doom/config-personal.org

**Comment by cashpw** [comment]
> Sorry for my ignorance: which section do you refer to?:
> https://github.com/cashpw/dotfiles/blob/main/config/doom/config-personal.org

I am away from my computer so I didn't originally include a link. This is the section: https://github.com/cashpw/dotfiles/blob/main/config%2Fdoom%2Fconfig-personal.org#completion-1. Specifically `company-idle-delay 1`.

**Comment by hpgisler** [comment]
> Turns out I misremembered and I have it set to a full second, not half a second.

I had also forgotten, that I already had that setting active, with 0.3s....

However, rather than prolonging that time, I think I would prefer the approach of having that mode enabled buffer local only. The reason being that I have 2 groups of files:
- project related, mainly containing headings with todo states
- knowledge related

I believe, that autocompletnion is not _that_ interesting for the project related files, as I usually look for and store a link explicitely of the target heading, and then insert it on the source side. For the knowledge related files I believe, it is interesting that the system notifies me of an entry already existing based on some wording used (usually nouns).

However, the `org-node-complete-at-point-mode` is a _global_ minor mode, I can not enable it exclusively for knowledge related files... Does there exist a technical rational that this mode must be global?

**Comment by meedstrom** [comment]
I suppose it can be local.

Just pushed a `org-node-complete-at-point-local-mode`, enjoy. For historical reasons, the old name will still refer to the global mode, for a few months.

**Comment by hpgisler** [comment]
> Just pushed a `org-node-complete-at-point-local-mode`, enjoy. 

Works great, thank you!
Now I do not get bothered anymore in my project files with knowledge files completion proposals.

The other way round would be much more difficult do so solve, I suppose:  
I.e. That I do not get bothered in my knowledge base files about completion proposals from my project files... right?

**Comment by meedstrom** [comment]
If you never want to access the project files with e.g. `org-node-find`, then you could configure `org-node-filter-fn` in such a way as to drop them all.

Out of curiosity, how many project nodes do you have?  And how many nodes total?

I have ~3000 total, so no matter which letter of the alphabet I start with, there's a sea of candidates.  In my mind, it's cleaner to roll with it than keep track of which buffer I am in.  

Many roads in the forest though.  It hasn't been a priority for me to support multiple separated "note piles".  With org-roam, I believe it is possible to hack that up with a .dir-locals.el file that sets the values of `org-roam-directory` and `org-roam-db-location`.

**Comment by hpgisler** [comment]
Good idea, to use `org-node-filter-fn` - I will try that. So this will not hinder the backlinks functionality? (because that I would like to keep in my project files, I can do without `org-node-find` in my project files, because I have 1 file per project, and thus project related search is easy)

FYI
Number of project nodes: ~1800
Total nodes: just slightly more, as I've just started with the knowledge base...

**Comment by meedstrom** [comment]
Won't affect backlinks, only completion. :)

**Comment by meedstrom** [comment]
Sidenote: I think I'll keep the old name referring to a global mode in perpetuity, it's not necessary to make people transition.
