### ISSUE TITLE
org-node--pop-to-tabulated-list: org-node--pop-to-tabulated-list: Mandatory arguments are buffer, format, entries

### ISSUE THREAD

**Issue by yaaama** [meedstrom/org-node#56]
This is the error I get after running `org-node-lint-all`
```
Lint 6 files? (y or n) y
org-node--pop-to-tabulated-list: org-node--pop-to-tabulated-list: Mandatory arguments are buffer, format, entries
```

It does not create a back-trace. The buffer displaying the org-lint results is not displayed.

Thank you

**Comment by meedstrom** [comment]
Oh, congratulations! You have no lint warnings at all.

Thanks for the report, I'll fix this.
