### ISSUE TITLE
Node title is not found for nodes with headings in `org-node-find`

### ISSUE THREAD

**Issue by christoffer-arvidsson** [meedstrom/org-node#57]
Hello! I'm liking the package so far, but I'm encountering a weird issue where in `org-node-find`, the titles of nodes are not found if the node itself contains any headings. Lots of my notes lack headings, so it makes searching a bit difficult

# Minimal example

File 1: `my_directory/20201024111012-test_does_not_find_title.org`
```org
:PROPERTIES:
:ID:       a2fb5512-051f-4e00-baab-51326bcafd97
:END:

#+TITLE: Does not find title

* my header
```
File 2: `my_directory/20201024111012-test_finds_title.org`
```org
:PROPERTIES:
:ID:       133c0995-cb25-46c9-bdb5-707db712f4c9
:END:

#+TITLE: Finds title
```

- If `org-node-alter-candidates` is `t`, then running `org-node-find` on this shows only the filename for the first example (so not the title), and the title for the second example
```
2 possible completions:
20201024111012-test_does_not_find_title.org
Finds title
```

- If `org-node-alter-candidates` is `nil`, then there's an error `#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_56>: Wrong type argument: stringp, nil` 

## Config

```elisp
(setq package-archives '(("gnu-devel" . "https://elpa.gnu.org/devel/")
                         ("melpa" . "https://melpa.org/packages/")
                         ("melpa-stable" . "https://stable.melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))
(setq custom-file "/tmp/custom.el")

(use-package org
  :ensure t)

(use-package org-node
  :ensure t
  :after org
  :custom
  (org-node-alter-candidates t)  ; set to nil for error
  (org-node-extra-id-dirs '("<path-to-my-directory>"))
  :config
  (org-node-cache-mode))

```

- GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.0)
- Org mode version 9.6.15 (release_9.6.15)
- Org node version: 1.2.6 (3ca5a95)

**Comment by meedstrom** [comment]
Thanks for the report! I can reproduce it. Fix will be in later today, I got a series of local commits to clean up first. :)

It works correctly if your files' front matter have no blank line, right? Like:

    :PROPERTIES:
    :ID:       133c0995-cb25-46c9-bdb5-707db712f4c9
    :END:
    #+TITLE: Finds title
    
    * Heading

**Comment by christoffer-arvidsson** [comment]
> In the meantime, it works correctly if your files' front matter have no blank line, right? Like this example
Aha, yep looks like that's the reason, not anything regarding headings :+1:
