### ISSUE TITLE
1.4.1 fails org-node--scan-all

### ISSUE THREAD

**Issue by daym** [meedstrom/org-node#60]
org-node 1.4.1 fails on org-node--scan-all with:

```
Lisp error: (wrong-type-argument listp 1725715909)
  cdr(1725715909)
  (+ total (cdr v))
  (setq total (+ total (cdr v)))
  (closure ((total . 0)) (_ v) (setq total (+ total (cdr v))))("~/doc/org-roam/df36f74a-f028-4165-9b1f-2d719ad859c..." 1725715909)
```

**Comment by meedstrom** [comment]
Did you by any chance upgrade the package without restarting Emacs? That is my first idea for how this could be occurring.

**Comment by daym** [comment]
Might be org-node--file<>mtime.elapsed

**Comment by daym** [comment]
Nuking org-node--file<>mtime.elapsed via 
`(setq org-node--file<>mtime.elapsed (make-hash-table :test #'equal))`
 makes it work once. Next time it will fail in the same way as before.

**Comment by daym** [comment]
Hmm, that can be. I run emacs in daemon mode.

**Comment by daym** [comment]
Nope, restarting the emacs daemon and then trying to use org-node makes it fail the same way.

**Comment by daym** [comment]
How does the following work?

```
    (cl-loop for (file . mtime.elapsed) in file-info
             do (puthash file mtime.elapsed org-node--file<>mtime.elapsed)
             ;; Transitional 2024-10-03 (remove in a couple of days)
             (puthash file (car mtime.elapsed) org-node--file<>mtime))
```

The hash table can only have one entry per key, no? And `file` is the key, right?

**Comment by meedstrom** [comment]
The parser used to just return an mtime like 1725715909 instead of a cons cell (1725715909 . TIME-ELAPSED). However, you should be automatically using the new version of the parser, since that's what's in 1.4.1. 

It tries to ensure that via `org-node--ensure-compiled-lib`, but I suppose it might not succeed in some cases.  Does it help if you eval these?

```elisp
(delete-file (org-node-parser--tmpfile "org-node-parser.elc"))

;; if native comp enabled, also this
(delete-file (comp-el-to-eln-filename (find-library-name "org-node-parser")))
```

**Comment by daym** [comment]
I evaluated those (without restarting emacs) and then doing M-x org-node-reset will fail the same way as before.

**Comment by meedstrom** [comment]
> The hash table can only have one entry per key, no? And `file` is the key, right?

Indeed, `file` is the key, and the value is supposed to be a cons cell.


Btw, you sure you restarted? Sometimes C-x C-c doesn't actually kill the daemon, surprisingly, but only the client. Try with `M-x save-buffers-kill-emacs`

**Comment by daym** [comment]
I had killed emacs via `pkill emacs`.

**Comment by meedstrom** [comment]
Not sure how `pkill` works, but hey :) Congratulations!

**Comment by daym** [comment]
I have now verified that after `pkill emacs` the emacs process is gone from `ps -ef`.

**Comment by meedstrom** [comment]
Maybe it only kills one process when you have multiple.

**Comment by daym** [comment]
I tried with two `cat` processes at the same time--and `pkill cat` and it killed both.

**Comment by daym** [comment]
Thanks for the help!

It's totally mysterious what happened here, though. So pkill did probably kill it before too.

What was it with those cache files in /tmp and /home ?

That sounds like I bad idea. I installed emacs-org-node from a Guix package and that does native compilation on its own in a system directory. What was the other thing?

**Comment by meedstrom** [comment]
I guess it might have to do with the regular `pkill` sending a SIGKILL or something which is polite and gives the program a chance to "handle" the signal, like prompting the user to save before exiting.  `pkill -9` (SIGTERM) for the win.

**Comment by meedstrom** [comment]
I don't know about /home, but in /tmp/org-node/ there are just temporary work files. I've used Guix in the past and I believe its operation won't be affected.

Good point about the 1970 timestamps. But your org files do not have 1970 timestamps, right? ;) it's just your installed software.

As for ensuring to have the newest compiled software via `(org-node--ensure-compiled-lib)`, it's mainly handy during development. If installing via Guix, then the up-to-date org-node-parser.eln should exist in load path anyway. Provided you restart emacs, of course :)

**Comment by meedstrom** [comment]
On second thought, Guix might not pre-compile the .eln files. I should think about how the behavior works then.

**Comment by meedstrom** [comment]
(I mixed up SIGTERM and SIGKILL, the former is the polite one.)

I've now removed the old `org-node--file<>mtime` table, should make the code easier to read.

Thanks for pointing out the 1970 thing. Now it's my bedtime, but welcome to file more issues!

**Comment by daym** [comment]
guix doesn't seem to precompile the eln files. That used to work.

I think it's a guix bug and you shouldn't need to work around it.

**Comment by meedstrom** [comment]
Fortunately `comp-el-to-eln-filename` hashes the file contents, so the timestamps won't be an issue.

> That used to work. I think it's a guix bug 

Guix can't make .eln on the build server, it has to happen on your computer, so it's probably controlled by settings like `native-comp-always-compile`.  Maybe it used to do it when you had to compile the emacs-with-libgccjit locally anyway.  I assume Guix ships a prebuilt binary nowadays so it has to wait until you start Emacs the first time.

**Comment by daym** [comment]
There the fascinating patch series at https://issues.guix.gnu.org/72406 (and a previous more high-level bug report https://issues.guix.gnu.org/72333 )

I think the source of the problem in this issue 60 here was this:

    (if (and native-path (file-newer-than-file-p native-path lib))
        ;; The .eln is fresh, use it
        native-path <--- uh oh

If there's a native lib from a previous run, `lib` will have a 1970 timestamp regardless of how many times guix updated it. Therefore, "The .eln is fresh, use it" will use the compile eln again--which is the wrong one.

**Comment by meedstrom** [comment]
native-path will be nil though because of comp-el-to-eln-filename

**Comment by meedstrom** [comment]
sorry, not nil, but different

**Comment by meedstrom** [comment]
it occurs to me there may be no need to do a file-newer-than-file-p check
at all

**Comment by daym** [comment]
Aha, Guix messed with comp-el-to-eln-rel-filename, see emacs-native-comp-fix-filenames.patch in https://lists.gnu.org/archive/html/guix-patches/2024-01/msg02082.html (which is in master)

**Comment by meedstrom** [comment]
Interesting, thanks for finding that. Can you try running
`comp-el-to-eln-filename` on your initfile, then edit the initfile and
save, then running it again, and seeing if the output differs?

**Comment by meedstrom** [comment]
Concerning. Just emailed bug-guix, I'll edit this comment when it shows up in the public archive.

**Comment by meedstrom** [comment]
I've refactored this function in 1.5.6, let me know if it broke.

https://github.com/meedstrom/org-node/commit/5a69f3b13dbd70110ce1cf97b629f6e98b0d8c2d
