### ISSUE TITLE
No, this doesn't work on windows-nt

### ISSUE THREAD

**Issue by JayDugger** [meedstrom/org-node#64]
https://github.com/meedstrom/org-node/blob/3241743c4b3d0c69968b301e62cb0602932297da/org-node.el#L1026

Seems to work fine on Linux,
but not on the Windows build of emacs where echo is not in the PATH.

What can I do to help?

**Comment by meedstrom** [comment]
Hi, thanks for reporting!  I got that command from here: https://stackoverflow.com/a/32395352

Are you using Emacs through Cygwin or WSL or an Emacs built for Windows? Maybe that affects the PATH.

What happens if you open the Command Prompt in Windows and enter `echo %NUMBER_OF_PROCESSORS%`?

**Comment by JayDugger** [comment]
GNU Emacs 29.4 (build 2, x86_64-w64-ming32) of 2024-07-05

Emacs built for Windows
Probably affects PATH

In cmd prompt,
echo %NUMBER_OF_PROCESSORS%
returns
8.

**Comment by meedstrom** [comment]
How did you figure that it does not work?

But another idea to try: in Emacs, can you eval the expression (getenv "%NUMBER_OF_PROCESSORS%")?  Would simplify the code.

**Comment by JayDugger** [comment]
Emacs now does something it didn't do for the previous version of the
package.

It returns

File error: Spawning child process, Exec format error

Evaluated your suggestion,
got

nil

Compared with emacs on WSL,
no problem there

**Comment by meedstrom** [comment]
Thanks.

I assume that this returns the integer 8:

```elisp
(ignore-errors
  (with-temp-buffer
    (call-process "echo" nil t nil "%NUMBER_OF_PROCESSORS%")
    (buffer-string)))
```

> File error: Spawning child process, Exec format error

When does this error occur? Can you do `M-x toggle-debug-on-error` and try to trigger it again?

**Comment by JayDugger** [comment]
The (ignore-errors) returned nothing.

In eshell
env returns the whole environment which includes the correct value for the
environment variable number of processors

I can trigger the error with org-node-reset. It also appears when starting
emacs.

With toggle-debug-error set,

Org-node--scan: Spawning child process: Exec format error

**Comment by meedstrom** [comment]
Hi, sorry for delaying. I've added instructions for how to downgrade org-node version on the README: https://github.com/meedstrom/org-node#how-to-rollback  

I'm currently spinning out a part of the codebase into a new library ([el-job](https://github.com/melpa/melpa/pull/9225)). Once that's done, it'll be easier for me to look into the error you're having.

By the way, regarding the number of processors.  Found a function that's built into Emacs! `(num-processors)` I hope that one returns an integer 8?

**Comment by JayDugger** [comment]
Thank you for your work on this issue.
I appreciate the roll back instructions.
(num-processors) returns 8

**Comment by meedstrom** [comment]
Do you still get the ”Exec format error”
on the latest version?

**Comment by JayDugger** [comment]
I was able to update to the most recent version last Friday, but I have not
yet extensively tested it beyond restarting emacs a few times.

So far so good, and thank you for putting in all the work into this
project. I suggest closing this issue. If I run into a problem I can open a
new one.

**Comment by meedstrom** [comment]
Alright, have a good day :)
