### ISSUE TITLE
Request: more flexibility in org-node-capture-target

### ISSUE THREAD

**Issue by alanz** [meedstrom/org-node#65]
Currently, the `org-node-capture-target` function has hard-coded values for the with-title and without-title options

https://github.com/meedstrom/org-node/blob/fe07328ff2e01abfde9e4e94354a7a240141314d/org-node.el#L2189-L2199

Perhaps this could instead be a function (like `org-node-creation-fn`) that takes an `id` and optional `title` and returns the content.

This allows easy customisation of additional headers.  e.g. I like to add `:last_modified: ` which is automatically updated when I save the file.

**Comment by meedstrom** [comment]
Thanks for suggestion! 

To clarify, you update `:last_modified:` every time you save a file? For all subtrees in the file?

If it is just something to run at capture time, not every save, then `org-node-creation-hook` could help you.

e.g.

```elisp
(add-hook 'org-node-creation-hook
          (defun my-update-last-modified ()
            (org-entry-put nil "last_modified"
                           (format-time-string (org-time-stamp-format t t)))))
```

**Comment by alanz** [comment]
The `:last_modified:` is just an example of the kinds of things that a separate function could be used for.

FYI, I use it like this

```elisp
;; From https://org-roam.discourse.group/t/update-a-field-last-modified-at-save/321/2
(use-package time-stamp
  :after org
  :config
  (add-hook 'org-mode-hook (lambda ()
                             (setq-local time-stamp-active t
                                         time-stamp-line-limit 18
                                         time-stamp-start "^:last_modified: [ \t]*"
                                         time-stamp-end "$"
                                         time-stamp-format "\[%Y-%m-%d %a %H:%M:%S\]")
                             (add-hook 'before-save-hook 'time-stamp nil 'local)))
  (add-hook 'write-file-functions 'time-stamp) ; update when saving
  )
```

**Comment by alanz** [comment]
And reading more closely, I think a hook function can be used to do what I want.  Thanks.

My context for this is trying to get the org-protocol capture working that org-roam has, without using `org-node-fakeroam`.  Which is as much about forcing myself to understand how it all works as solving a real problem.

**Comment by meedstrom** [comment]
Good luck :) 

I agree a hook seems cleaner in this case, but I could definitely use feedback on the capture and refile stuff, I'm not a heavy user of these things. Let me know if something needs to change to fit with org-protocol.

**Comment by alanz** [comment]
I managed to hack something ugly together that does what I need.  Thanks for the pointers.
