### ISSUE TITLE
Error: Search failed: ":"

### ISSUE THREAD

**Issue by oatmealm** [meedstrom/org-node#7]
Wondering what does this message means? I'm unable to search thus far...

```
First run and no cache, caching synchronously...
org-node resetting... inspected 2574/8212 files
Search failed: ":"
```

**Comment by meedstrom** [comment]
Thanks for the report! Looking into it.

**Comment by meedstrom** [comment]
I added some error checks, so if you try again we may learn more!

It may be a malformed property drawer in one of your files (I get those too), or a different bug :)

**Comment by oatmealm** [comment]
Works! Love the idea btw. So far I'm tracking the repo and trying to use org-node occasionally... love the added org-transclude support, nice feature !

**Comment by meedstrom** [comment]
yeah I thought that was pretty neat! Feel free to report more bugs.
