### ISSUE TITLE
error: "Items split in 13 lists, but only 11 ready processes"

### ISSUE THREAD

**Issue by jyp** [meedstrom/org-node#73]
I am getting the error:
```
Error running timer ‘org-node--scan-all’: (error "Items split in 13 lists, but only 11 ready processes")
```

Version of el-job: 20241120.2102
Verson of org-node: 20241119.2031

Stack trace when running the function manually:
```
  error("Items split in %d lists, but only %d ready process..." 13 11)
  el-job--exec(#s(el-job :id org-node :anonymous nil :method reap :benchmark t :sig 2054615608406241534 :cores 11 :wrapup nil :ready ... :busy nil :stderr #<buffer  *el-job-org-node:err*> :timestamps ... :poll-timer ... :timeout ... :finish-times nil ...))
  el-job-launch(:id org-node :if-busy noop :load org-node-parser :inject-vars (($plain-re . "\\(?:\\<\\(https?\\|id\\):\\(\\(?:[^][ \11\n()<>]\\|[(<[]\\(?:...") ($merged-re . "\\[\\[\\(\\(?:[^][\\]\\|\\\\\\(?:\\\\\\\\\\)*[][]\\|\\\\+[^][]\\)+\\)...") ($assume-coding-system) ($inlinetask-min-level) ($file-todo-option-re . "^[[:space:]]*\\(?:#\\+\\(?:\\(?:\\(?:seq\\|typ\\)_\\)?todo...") ($global-todo-re . "\\(?:CANCELLED\\|DONE\\|HOLD\\|TODO\\|WAITING\\)") ($file-name-handler-alist) ($backlink-drawer-re . "^[\11 ]*:backlinks:")) :eval-once "(org-node-parser--init)" :funcall org-node-parser--collect-dangerously :inputs org-node-list-files :wrapup org-node--finalize-full)
  (if (el-job-is-busy 'org-node) nil (setq org-node--time-at-begin-full-scan (time-convert nil t)) (el-job-launch :id 'org-node :if-busy 'noop :load 'org-node-parser :inject-vars (append org-node-inject-variables (org-node--mk-work-vars)) :eval-once "(org-node-parser--init)" :funcall #'org-node-parser--collect-dangerously :inputs #'org-node-list-files :wrapup #'org-node--finalize-full))
  (unless (el-job-is-busy 'org-node) (setq org-node--time-at-begin-full-scan (time-convert nil t)) (el-job-launch :id 'org-node :if-busy 'noop :load 'org-node-parser :inject-vars (append org-node-inject-variables (org-node--mk-work-vars)) :eval-once "(org-node-parser--init)" :funcall #'org-node-parser--collect-dangerously :inputs #'org-node-list-files :wrapup #'org-node--finalize-full))
  org-node--scan-all()
  eval-expression((org-node--scan-all) nil nil 127)
  funcall-interactively(eval-expression (org-node--scan-all) nil nil 127)
  command-execute(eval-expression)
```

**Comment by meedstrom** [comment]
Thank you for the report, looking into it.

**Comment by meedstrom** [comment]
Pushed a possible fix to el-job (https://github.com/meedstrom/el-job/commit/940e8ff2e116f8ff55f3d354e55e6e4b9de85146).

Let me know if you still get the error.

**Comment by yaaama** [comment]
> Pushed a possible fix to el-job ([meedstrom/el-job@940e8ff](https://github.com/meedstrom/el-job/commit/940e8ff2e116f8ff55f3d354e55e6e4b9de85146)).
> 
> (you can use `M-x package-vc-install` if you don't want to wait for MELPA's build)
> 
> Let me know if you still get the error.

I am having the same issue, and I'm using the latest version, I've included a backtrac:

<details><summary>Details</summary>
<p>

Debugger entered--Lisp error: (error "Items split in 9 lists, but only 7 ready processes")
  (error "Items split in %d lists, but only %d ready processes" 9 7)
  (el-job--exec #s(el-job :id org-node :anonymous nil :method change-hook :benchmark t :sig 764586724389865454 :cores 7 :wrapup nil :ready (#<process el-job:org-node:4> #<process el-job:org-node:3> #<process el-job:org-node:2> #<process el-job:org-node:1> #<process el-job:org-node:0> #<process el-job:org-node:6> #<process el-job:org-node:5>) :busy nil :stderr #<buffer  *el-job-org-node:err*> :timestamps (:accept-launch-request (1732751405622368771 . 1000000000) :launched (1732751618690834204 . 1000000000) :children-done (1732751618693982410 . 1000000000) :got-all-results (1732751618721663166 . 1000000000)) :poll-timer [t nil nil nil nil nil nil nil nil nil] :timeout [nil 26439 45344 690837 nil el-job--timeout (org-node) nil 813000 nil] :finish-times nil :past-elapsed #<hash-table equal 10/24 0x1f464bd231cb ...> :spawn-args (#2 (org-node-parser) (($plain-re . "\\(?:\\<\\(https?\\|id\\):\\(\\(?:[^][ \11\n()<>]\\|[(<[]\\(?:[^][ \11\n()<>]\\|[(<[][^][ \11\n()<>]*[])>]\\)*[])>]\\)+\\(?:[^[:punct:][:space:]\n]\\|[/-]\\|[(<[]\\(?:[^][ \11\n()<>]\\|[(<[][^][ \11\n()<>]*[])>]\\)*[])>]\\)\\)\\)") ($merged-re . "\\[\\[\\(\\(?:[^][\\]\\|\\\\\\(?:\\\\\\\\\\)*[][]\\|\\\\+[^][]\\)+\\)]\\(?:\\[\\([^z-a]+?\\)]\\)?]\\|\\(?:\\<\\(https?\\|id\\):\\(\\(?:[^][ \11\n()<>]\\|[(<[]\\(?:[^][ \11\n()<>]\\|[(<[][^][ \11\n()<>]*[])>]\\)*[])>]\\)+\\(?:[^[:punct:][:space:]\n]\\|[/-]\\|[(<[]\\(?:[^][ \11\n()<>]\\|[(<[][^][ \11\n()<>]*[])>]\\)*[])>]\\)\\)\\)") ($assume-coding-system) ($inlinetask-min-level . 8) ($file-todo-option-re . "^[[:space:]]*\\(?:#\\+\\(?:\\(?:\\(?:seq\\|typ\\)_\\)?todo: \\)\\)") ($global-todo-re . "\\(?:CANCELLED\\|DONE\\|KILL\\|REVIEW\\|TODO\\|WAITING\\|\\[\\(?:[?X]]\\)\\|[][]\\)") ($file-name-handler-alist) ($backlink-drawer-re . "^[\11 ]*:backlinks:")) "(org-node-parser--init)" org-node-parser--collect-dangerously) :input-sets ((#<process el-job:org-node:0> "~/org/notes/wireguard.org" "/home/aayush/org/notes/hugo.org") (#<process el-job:org-node:1> "/home/aayush/org/notes/go-lang.org" "~/org/notes/Emacs-Lisp.org") (#<process el-job:org-node:2> "/home/aayush/org/projects.org") (#<process el-job:org-node:3> "~/org/notes/sh-script.org") (#<process el-job:org-node:4> "~/org/notes/linux.org" "~/org/refile.org") (#<process el-job:org-node:5> "/home/aayush/dotfiles/README.org") (#<process el-job:org-node:6> "/home/aayush/org/notes/C.org")) :queue ("~/org/notes/linux.org" "~/org/refile.org" "~/org/notes/sh-script.org" "/home/aayush/org/projects.org" "/home/aayush/org/notes/go-lang.org" "~/org/notes/Emacs-Lisp.org" "~/org/notes/wireguard.org" "/home/aayush/org/notes/hugo.org" "/home/aayush/org/notes/C.org" "/home/aayush/dotfiles/README.org") :results nil))
  (el-job-launch :id org-node :if-busy noop :load org-node-parser :inject-vars (($plain-re . "\\(?:\\<\\(https?\\|id\\):\\(\\(?:[^][ \11\n()<>]\\|[(<[]\\(?:[^][ \11\n()<>]\\|[(<[][^][ \11\n()<>]*[])>]\\)*[])>]\\)+\\(?:[^[:punct:][:space:]\n]\\|[/-]\\|[(<[]\\(?:[^][ \11\n()<>]\\|[(<[][^][ \11\n()<>]*[])>]\\)*[])>]\\)\\)\\)") ($merged-re . "\\[\\[\\(\\(?:[^][\\]\\|\\\\\\(?:\\\\\\\\\\)*[][]\\|\\\\+[^][]\\)+\\)]\\(?:\\[\\([^z-a]+?\\)]\\)?]\\|\\(?:\\<\\(https?\\|id\\):\\(\\(?:[^][ \11\n()<>]\\|[(<[]\\(?:[^][ \11\n()<>]\\|[(<[][^][ \11\n()<>]*[])>]\\)*[])>]\\)+\\(?:[^[:punct:][:space:]\n]\\|[/-]\\|[(<[]\\(?:[^][ \11\n()<>]\\|[(<[][^][ \11\n()<>]*[])>]\\)*[])>]\\)\\)\\)") ($assume-coding-system) ($inlinetask-min-level . 8) ($file-todo-option-re . "^[[:space:]]*\\(?:#\\+\\(?:\\(?:\\(?:seq\\|typ\\)_\\)?todo: \\)\\)") ($global-todo-re . "\\(?:CANCELLED\\|DONE\\|KILL\\|REVIEW\\|TODO\\|WAITING\\|\\[\\(?:[?X]]\\)\\|[][]\\)") ($file-name-handler-alist) ($backlink-drawer-re . "^[\11 ]*:backlinks:")) :eval-once "(org-node-parser--init)" :funcall org-node-parser--collect-dangerously :inputs org-node-list-files :wrapup org-node--finalize-full)
  (org-node--scan-all)
  (apply org-node--scan-all nil)
  (timer-event-handler [t 0 31 412925 t org-node--scan-all nil idle 699999 nil])


</p>
</details>

**Comment by meedstrom** [comment]
Hmm. Thank you, I'll look some more. In the meantime, this override would fix so you don't get any error, if I'm right?

```elisp
(defun el-job--split-optimally (items n _table)
  (el-job--split-evenly items n))
```

**Comment by meedstrom** [comment]
Another possible fix pushed.

**Comment by jyp** [comment]
I am not seeing the error any longer, thanks!

**Comment by meedstrom** [comment]
Nevermind, there's still an issue. #78.

**Comment by meedstrom** [comment]
Solved.
