### ISSUE TITLE
org-node--scan-all problem with el-job 

### ISSUE THREAD

**Issue by scfrank-pri** [meedstrom/org-node#78]
About every 30 seconds, I receive the error message: 

```
Debugger entered--Lisp error: (error "Items split in 16 lists, but only 15 ready process...")
  error("Items split in %d lists, but only %d ready process..." 16 15)
  el-job--exec(#s(el-job :id org-node :anonymous nil :method reap :benchmark t :sig 2828373330973027432 :cores 15 :wrapup nil :ready (#<process el-job:org-node:14>  .... .... # :results nil))
  el-job-launch(:id org-node :if-busy noop :load org-node-parser :inject-vars (($plain-re . "\\(?:\\<\\(https?\\|id\\):\\(\\(?:[^][ \11\n()<>]\\|[(<[]\\(?:...") ($merged-re . "\\[\\[\\(\\(?:[^][\\]\\|\\\\\\(?:\\\\\\\\\\)*[][]\\|\\\\+[^][]\\)+\\)...") ($assume-coding-system) ($inlinetask-min-level) ($file-todo-option-re . "^[[:space:]]*\\(?:#\\+\\(?:\\(?:\\(?:seq\\|typ\\)_\\)?todo...") ($global-todo-re . "\\(?:DONE\\|IN-PROGRESS\\|TODO\\|WAITING\\)") ($file-name-handler-alist) ($backlink-drawer-re . "^[\11 ]*:backlinks:")) :eval-once "(org-node-parser--init)" :funcall org-node-parser--collect-dangerously :inputs org-node-list-files :wrapup org-node--finalize-full)
  org-node--scan-all()
```
I get the same with different numbers of nodes (9 lists, 8 ready process ....). No idea what to do with it.

**Comment by meedstrom** [comment]
What's the version of el-job? Or when it was updated.

**Comment by meedstrom** [comment]
If updating does not help, let me know if you see the same problem after

1. `M-x el-job--kill-all` 
2. `M-x org-node-reset`

**Comment by scfrank-pri** [comment]
> What's the version of el-job? Or when it was updated.

    Status: Installed in ‘el-job-20241201.1208/’ (unsigned).
    Version: 20241201.1208


> If updating does not help, let me know if you see the same problem after
> 
>     1. `M-x el-job--kill-all`
> 
>     2. `M-x org-node-reset`

I did so and restarted emacs, but the problem remains: `(error "Items split in 16 lists, but only 15 ready process...")`

**Comment by scfrank-pri** [comment]
The last update has fixed the problem. Thank you
